### ISSUE TITLE
Non-uniform colours on gradients in top + bottom of thumbnails

### ISSUE THREAD

**Issue by LiamSouthwell** [LiamSouthwell/mysurf.tv#17]
![image](https://user-images.githubusercontent.com/17756834/57965362-ac9c1700-7986-11e9-8b87-f6c1c615f7f0.png)
Makes images that have been letterboxed to preserve 16:9 aspect ratio look very off

**Comment by LiamSouthwell** [comment]
Also the colour is off brand

**Comment by wasifchowdhury-griffith** [comment]
changed both overlays to be logo colour (#2d3f51)
