### ISSUE TITLE
Border doesn't affect position of text in Videolist thumbnails

### ISSUE THREAD

**Issue by LiamSouthwell** [LiamSouthwell/mysurf.tv#19]
![image](https://user-images.githubusercontent.com/17756834/57965390-e8cf7780-7986-11e9-9095-da7652ea03b7.png)

Unsure if border is meant to look that way but if we're keeping it, the text shouldn't overlap

**Comment by wasifchowdhury-griffith** [comment]
removed border, added padding to text
