### ISSUE TITLE
Text colour isn't on brand

### ISSUE THREAD

**Issue by LiamSouthwell** [LiamSouthwell/mysurf.tv#20]
![image](https://user-images.githubusercontent.com/17756834/57965398-0d2b5400-7987-11e9-93bb-34fdc000d3d8.png)

vs

![image](https://user-images.githubusercontent.com/17756834/57965400-16b4bc00-7987-11e9-9915-006da431a1c1.png)

**Comment by wasifchowdhury-griffith** [comment]
fixed header colour to be same as logo
